### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by dwakeparkfield** [irbyjm/trakt-discord-presence#12]
I've got Python3 installed on Windows, with the 2 prerequisites. I've done the init file and it's authed properly.

I keep getting the following error.

`PS F:\trakt-discord-presence-master> python .\trakt_discord.py jonathanTF2 <client ID>
2019-08-29T21:27:47.000GMT Summer Time : Successfully connected to Trakt
Traceback (most recent call last):
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 97, in close
    self.send({}, op=OP_CLOSE)
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 120, in send
    self._write(header)
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 202, in _write
    self._f.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\trakt_discord.py", line 45, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 54, in for_platform
    return WinDiscordIpcClient(client_id)
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 48, in __init__
    self._do_handshake()
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 70, in _do_handshake
    self.close()
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 99, in close
    self._close()
  File "F:\trakt-discord-presence-master\lib\rpc.py", line 208, in _close
    self._f.close()
OSError: [Errno 22] Invalid argument
PS F:\trakt-discord-presence-master>`

**Comment by irbyjm** [comment]
I can look at this later tonight--but off the top of my head, are you appending the discord client id at the end of `F:\trakt-discord-presence-master> python .\trakt_discord.py jonathanTF2` and sanitizing it?

The app invocation should be: `./trakt_discord.py <trakt username> <discord client id>`

**Comment by JonathanTF2** [comment]
Yeah, I am, just removed the ID for the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by irbyjm** [comment]
Do you have a Discord software client (not in-browser) running before you start the app? I see it's closing out during the local client handshake.

**Comment by JonathanTF2** [comment]
Yep, I've got it running.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by irbyjm** [comment]
Make sure you're passing the Discord client_id to the python script and not the Trakt client_id. I accidentally pasted the wrong one in and was getting the exact error that you're having--after getting the right id from https://discordapp.com/developers/applications/ , the script works for me.

PS: I've never ran this script under Windows, so thanks for making me do it.

**Comment by JonathanTF2** [comment]
Yep, I'm passing the client ID from Discord Developers. I wanted to use the script from my Linux VPS but you need Discord running for this to work

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by irbyjm** [comment]
I'm sorry, I'm unable to reproduce this.

I've reset my 2FA to see if that was messing things up, but with it on and off I'm still able to run the app. Please ensure the Discord app is listening on TCP/6463 as this is the Discord RPC port. Aside from that, I can only suggest running through the Discord Application creation again, perhaps just hitting Regenerate on the Client ID.
