### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by Flavien06** [irbyjm/trakt-discord-presence#14]
Hi, 
I have this error. Any idea why?

```
sudo ./trakt_discord.py ***** *****************
2020-05-05T13:00:41.000CEST : Successfully connected to Trakt
Traceback (most recent call last):
  File "./trakt_discord.py", line 45, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 56, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 48, in __init__
    self._do_handshake()
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 64, in _do_handshake
    {'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 112, in send_recv
    self.send(data, op)
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 120, in send
    self._write(header)
  File "/home/pi/trakt-discord-presence/lib/rpc.py", line 242, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
```

**Comment by irbyjm** [comment]
I believe the most likely cause of Errno 107 is not having a Discord client running on the same machine as the script. The script does not need to run on the same machine that is playing media but it does need to run on a machine with Discord up.

**Comment by Flavien06** [comment]
I don't think so, the script is run from a raspberry pi

**Comment by irbyjm** [comment]
This is currently one limitation I've not yet worked around, sorry!
